version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - scanner_net

  frontend:
    build: ./frontend
    ports:
      - "3000:4173"
    depends_on:
      - backend
    networks:
      - scanner_net

networks:
  scanner_net:
    driver: bridge
